# Site settings
title: Lourdgene Howes
email:
description: Lourdgene Howes
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.e-seafoods.com" # the base hostname & protocol for your site

# Build settings
markdown: kramdown

#Collections
collections:
  product:
    output: true
    permalink: products/:path/

navbar-menu:
  - title: Accessories
    slug-link: accessories

  - title: Cheeks
    slug-link: cheeks

  - title: Eyes
    slug-link: eyes

  - title: Face
    slug-link: face

  - title: Lips
    slug-link: lips

  - title: Makeup Bags
    slug-link: makeupbag

  - title: Skin Care
    slug-link: makeupbag

  - title: "Tools & Brushes"
    slug-link: tools


